apiVersion: 1

datasources:
  - name: loki
    type: loki
    url: loki:3100
    access: proxy
    isDefault: false

  - name: postgres
    type: postgres
    url: postgres:5432
    database: movie_database
    user: grafana
    basicAuth: false
    jsonData:
       sslmode: disable
    secureJsonData:
       password: "grafana"
    version: 1
    editable: true